### ISSUE TITLE
Watcher created but we can't find 

### ISSUE THREAD

**Issue by nicoclau** [sentinl/sentinl#808]
We create the watcher we get the message: watcher saved: 466a5440-9d88-11ed-92a0-218559ad6ff1

But it is not in the table and not returned with https://xxx/api/sentinl/list/watchers

Can you tell us why?
Thanks

**Comment by nicoclau** [comment]
It was because we had a limit of number of alerts.
We changed it to a higher number now we can see our watcher.

**Comment by lmangani** [comment]
You're still using sentinl? @nicoclau

**Comment by nicoclau** [comment]
I do still use sentinl

**Comment by lmangani** [comment]
> I do still use sentinl

That's interesting, impressive and a little scary even considering we stopped developing it almost 4 years ago. I'm proud of our work being able to survive this far and still be useful to anyone, but I'm even more curious as of why you still use it? Is it because you're stuck on an older version of ES or because of its features? Thanks for your input 👍
